# Generated by Django 4.1.7 on 2023-02-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0003_order_item_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.CharField(default='Test', max_length=100, verbose_name='Cart name'),
        ),
    ]
