# Generated by Django 4.1.7 on 2023-02-18 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0004_order_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='usd', max_length=150, verbose_name='Currency')),
                ('percent_off', models.FloatField(default=25, max_length=150, verbose_name='Percent off')),
                ('duration', models.CharField(default='repeating', max_length=150, verbose_name='Duration')),
                ('duration_in_months', models.IntegerField(default=3, verbose_name='Duration in months')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Tax',
                'verbose_name_plural': 'Tax',
            },
        ),
        migrations.RenameField(
            model_name='order',
            old_name='cart',
            new_name='cart_name',
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='Payment.discount'),
        ),
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='Payment.tax'),
        ),
    ]
