# Generated by Django 4.1.7 on 2023-02-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0005_discount_tax_rename_cart_order_cart_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='category',
            field=models.CharField(choices=[('Tangible Goods', 'txcd_99999999'), ('Electronically Supplied Services', 'txcd_10000000'), ('Services', 'txcd_20030000')], default='Tangible Goods', max_length=50, verbose_name='Category'),
        ),
    ]
