# Generated by Django 4.1.7 on 2023-02-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0006_tax_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='category',
            field=models.CharField(choices=[('txcd_99999999', 'Tangible Goods'), ('txcd_10000000', 'Electronically Supplied Services'), ('txcd_20030000', 'Services')], default='txcd_99999999', max_length=50, verbose_name='Category'),
        ),
    ]
